title: miniscule.
description: > # this means to ignore newlines until "show_excerpts:"
  a clean and light jekyll theme

author:
  name: filbert phang
  thumb: assets/miniscule.png

collections:
  - features

show_excerpts: false   # set to true to show excerpts on the homepage
one_page_header: true  # set to true to have the header display links to features instead of pages
slide_out_footer: false

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  "filbertphang/miniscule"
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll
    email: name@domain.com

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

plugins:
 - jekyll-feed
 - jekyll-seo-tag
